# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commu.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='commu.proto',
  package='ivi',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0b\x63ommu.proto\x12\x03ivi\":\n\x05Login\x12\x0f\n\x07\x44\x65vType\x18\x01 \x01(\t\x12\x0f\n\x07TableId\x18\x02 \x01(\t\x12\x0f\n\x07Version\x18\x03 \x01(\t\")\n\nLoginReply\x12\r\n\x05\x65rror\x18\x01 \x01(\r\x12\x0c\n\x04\x43uid\x18\x02 \x01(\t\"\x19\n\tHeartInfo\x12\x0c\n\x04\x43uid\x18\x01 \x01(\t\"\x94\x01\n\x12\x44\x65tectRecordConfig\x12\x0c\n\x04\x43uid\x18\x01 \x01(\t\x12\x12\n\nIsCleanImg\x18\x02 \x01(\x08\x12\x12\n\nIsCleanLog\x18\x03 \x01(\x08\x12\x12\n\nIsCleanCSV\x18\x04 \x01(\x08\x12\x10\n\x08SaveDays\x18\x05 \x01(\r\x12\x11\n\tCleanTime\x18\x06 \x01(\t\x12\x0f\n\x07TableId\x18\x07 \x01(\t\"6\n\x17\x44\x65tectRecordConfigReply\x12\r\n\x05\x65rror\x18\x01 \x01(\r\x12\x0c\n\x04\x43uid\x18\x02 \x01(\tb\x06proto3'
)




_LOGIN = _descriptor.Descriptor(
  name='Login',
  full_name='ivi.Login',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='DevType', full_name='ivi.Login.DevType', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TableId', full_name='ivi.Login.TableId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Version', full_name='ivi.Login.Version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=78,
)


_LOGINREPLY = _descriptor.Descriptor(
  name='LoginReply',
  full_name='ivi.LoginReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='ivi.LoginReply.error', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Cuid', full_name='ivi.LoginReply.Cuid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=121,
)


_HEARTINFO = _descriptor.Descriptor(
  name='HeartInfo',
  full_name='ivi.HeartInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Cuid', full_name='ivi.HeartInfo.Cuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=148,
)


_DETECTRECORDCONFIG = _descriptor.Descriptor(
  name='DetectRecordConfig',
  full_name='ivi.DetectRecordConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Cuid', full_name='ivi.DetectRecordConfig.Cuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IsCleanImg', full_name='ivi.DetectRecordConfig.IsCleanImg', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IsCleanLog', full_name='ivi.DetectRecordConfig.IsCleanLog', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IsCleanCSV', full_name='ivi.DetectRecordConfig.IsCleanCSV', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SaveDays', full_name='ivi.DetectRecordConfig.SaveDays', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CleanTime', full_name='ivi.DetectRecordConfig.CleanTime', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TableId', full_name='ivi.DetectRecordConfig.TableId', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=299,
)


_DETECTRECORDCONFIGREPLY = _descriptor.Descriptor(
  name='DetectRecordConfigReply',
  full_name='ivi.DetectRecordConfigReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='ivi.DetectRecordConfigReply.error', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Cuid', full_name='ivi.DetectRecordConfigReply.Cuid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=301,
  serialized_end=355,
)

DESCRIPTOR.message_types_by_name['Login'] = _LOGIN
DESCRIPTOR.message_types_by_name['LoginReply'] = _LOGINREPLY
DESCRIPTOR.message_types_by_name['HeartInfo'] = _HEARTINFO
DESCRIPTOR.message_types_by_name['DetectRecordConfig'] = _DETECTRECORDCONFIG
DESCRIPTOR.message_types_by_name['DetectRecordConfigReply'] = _DETECTRECORDCONFIGREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Login = _reflection.GeneratedProtocolMessageType('Login', (_message.Message,), {
  'DESCRIPTOR' : _LOGIN,
  '__module__' : 'commu_pb2'
  # @@protoc_insertion_point(class_scope:ivi.Login)
  })
_sym_db.RegisterMessage(Login)

LoginReply = _reflection.GeneratedProtocolMessageType('LoginReply', (_message.Message,), {
  'DESCRIPTOR' : _LOGINREPLY,
  '__module__' : 'commu_pb2'
  # @@protoc_insertion_point(class_scope:ivi.LoginReply)
  })
_sym_db.RegisterMessage(LoginReply)

HeartInfo = _reflection.GeneratedProtocolMessageType('HeartInfo', (_message.Message,), {
  'DESCRIPTOR' : _HEARTINFO,
  '__module__' : 'commu_pb2'
  # @@protoc_insertion_point(class_scope:ivi.HeartInfo)
  })
_sym_db.RegisterMessage(HeartInfo)

DetectRecordConfig = _reflection.GeneratedProtocolMessageType('DetectRecordConfig', (_message.Message,), {
  'DESCRIPTOR' : _DETECTRECORDCONFIG,
  '__module__' : 'commu_pb2'
  # @@protoc_insertion_point(class_scope:ivi.DetectRecordConfig)
  })
_sym_db.RegisterMessage(DetectRecordConfig)

DetectRecordConfigReply = _reflection.GeneratedProtocolMessageType('DetectRecordConfigReply', (_message.Message,), {
  'DESCRIPTOR' : _DETECTRECORDCONFIGREPLY,
  '__module__' : 'commu_pb2'
  # @@protoc_insertion_point(class_scope:ivi.DetectRecordConfigReply)
  })
_sym_db.RegisterMessage(DetectRecordConfigReply)


# @@protoc_insertion_point(module_scope)
